import './styles/index.scss';
import './styles/blog.scss';
import './styles/contact.scss';
import './styles/footer.scss';
import './styles/media.scss';
import './styles/portfolio.scss';
import './styles/pricing.scss';
import './styles/services.scss';
import './styles/team.scss';